### ISSUE TITLE
not able to extract strings 

### ISSUE THREAD

**Issue by nileshzala005** [biesbjerg/ngx-translate-extract#163] opened 2020-01-29 12:06 UTC
/@biesbjerg/ngx-translate-extract/dist/utils/ast-helpers.js:76
        return expression.elements.reduce((result, element) => {
                                   ^

TypeError: Cannot read property 'reduce' of undefined

**Comment by DavidCMeier** [comment] 2020-02-10 08:10
same error here :_(

**Comment by DavidCMeier** [comment] 2020-02-10 08:45
I checked the code and the problem is in "isArrayLiteralExpression". i modify in the code and use: 

in ast-helper, function getStringsFromExpression(expression):
`if(expression.elements) return expression.elements.reduce((result, element) => {`

that is working, but is never enter on the method because never exist elements on expression.

**Comment by jochenjonc** [comment] 2020-03-04 08:12
See #166, probably it can be temporarily solved in the same manner.

**Comment by biesbjerg** [comment] 2020-03-08 09:13
Could someone please provide a full example of a file that results in the error when trying to extract strings from it?

**Comment by biesbjerg** [comment] 2020-03-19 10:24
Closing since I cannot reproduce.

**Closed by biesbjerg** 2020-03-19 10:24 UTC
