### ISSUE TITLE
Failed to extract with markers added

### ISSUE THREAD

**Issue by roboter** [biesbjerg/ngx-translate-extract#155] opened 2019-11-20 12:56 UTC
When I add the marker it crashes:
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appextract-translations: `ngx-translate-extract --marker _ --input ./src --output ./src/assets/locale/en.json --clean --sort --format namespaced-json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the [app] extract-translations script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Without `--marker _` seems fine

**Comment by roboter** [comment] 2019-11-20 13:00
_('FEEDBACK.thankyou-msg'); - works fine

fails:
      this.translateService.get(_('FEEDBACK.thankyou-msg')).subscribe((res: string) => {
        this.presentToast(res);
      });

**Comment by roboter** [comment] 2019-11-20 13:01
ast-helpers.js:76
        return expression.elements.reduce((result, element) => {
                                   ^

**Comment by TekSiDoT** [comment] 2019-12-12 16:10
A couple of observations:
* I tried your code alongside the other tests in marker.parser.spec.ts without any problems
* ngx-translate-extract automatically detects your custom marker in the import statement of each file, the ´--marker´ argument is not necessary.

I also added your code samples to a larger project and extracted them without a problem (irrespective of whether or not using the ´--marker´ argument.

**Comment by orlyapps** [comment] 2019-12-18 08:16
> ast-helpers.js:76
> return expression.elements.reduce((result, element) => {
> TypeError: Cannot read property 'reduce' of undefined

same problem here

**Comment by TekSiDoT** [comment] 2019-12-18 10:03
Could you supply a minimal reproduceable example?

**Comment by roboter** [comment] 2019-12-18 14:53
https://github.com/roboter/IonicTestApp/tree/ngx-translate-extract-error

**Comment by roboter** [comment] 2019-12-18 15:07
constructor(public feedbackService: TranslateService) { }

removing constructor and it works

**Comment by plaramee1** [comment] 2020-02-11 19:23
Any progress here ? I have the same issue using the marker...
`this._translate.get(_i18n('client.header')).subscribe(value => {`


I also found a weird bug using Angular Material mat-button...
this will work : 
`<button mat-button (click)="search()">{{ 'client.search.searchBtn' | translate }}</button>`
this wont :
`<button mat-button (click)="search()" translate>client.search.searchBtn</button>`

**Comment by jscti** [comment] 2020-03-05 10:16
Doesn't work either .. and it can't be simplier :

```typescript
import { marker } from '@biesbjerg/ngx-translate-extract-marker';

export class AppModule {
    constructor() {
        marker('DYNAMIC_TRAD.val1');
        marker('DYNAMIC_TRAD.val2');
    }
}
```

and command `ngx-translate-extract --input ./src/app --output ./src/assets/i18n/locale-*.json --clean --sort --format namespaced-json --format-indentation '    '`

**Comment by jscti** [comment] 2020-03-05 10:32
Fun fact, it doesn't  work either with : 

```typescript
@NgModule({
    bootstrap: [
        AppComponent
    ],
    imports: [
        NativeScriptModule,
        TranslateModule.forRoot({
            loader: { provide: TranslateLoader, useClass: CustomLoader }
        }),
    ],
})
export class AppModule {
    constructor(private translate: TranslateService) {
        translate.instant('DYNAMIC_TRAD.val1');
        translate.instant('DYNAMIC_TRAD.val2');
    }
}
```

**Comment by biesbjerg** [comment] 2020-03-22 09:56
> ```ts
>         translate.instant('DYNAMIC_TRAD.val1');
>         translate.instant('DYNAMIC_TRAD.val2');
> ```

For now, you need to use `this.translate.instant(' ... ') for it to be picked up by the parser.

**Comment by biesbjerg** [comment] 2020-03-22 10:13
@roboter 

I checked out your app and the reason it is crashing is because it has errors and doesn't compile.

ngx-translate is not installed nor imported in your component. The reason you don't get an error when removing the marker is that `ngx-translate-extract` skips the file, since there is nothing to extract.

Closing since it works as intended (though you could argue a better error message would be nice).

I added a couple of tests of cases reported not working in this issue, and all works for me.

https://github.com/biesbjerg/ngx-translate-extract/commit/b07d929484240a37780fd6bc457e4ed6877889a0

**Closed by biesbjerg** 2020-03-22 10:13 UTC
