### ISSUE TITLE
Should ignore backslash escaping character when extracting from string

### ISSUE THREAD

**Issue by Toub** [biesbjerg/ngx-translate-extract#42] opened 2017-05-05 06:48 UTC
The following template, in French, contains a backslash that should be ignored during the extraction:

```html
[title]=" 'C\'est ok' | translate"
```
Actual extraction:

```po
msgid "C\\'est ok"
```
Expected: 

```po
msgid "C'est ok"
```

**Comment by BenDevelopment** [comment] 2017-06-27 10:06
As a french, I really need this too!

**Comment by BenDevelopment** [comment] 2017-06-27 11:38
The problem comes from the replace method which only replaces the first occurrence of matched string.
This code:
```
while (matches = regExp.exec(template)) {
	collection = collection.add(matches[2].replace('\\\'', '\''));
}
```
Should be replaced by this code:
```
while (matches = regExp.exec(template)) {
	collection = collection.add(matches[2].split('\\\'').join('\''));
}
```
Can someone fix this (@biesbjerg)?

**Comment by biesbjerg** [comment] 2017-07-05 13:31
@BenDevelopment Since I don't have much time at the moment, a PR with a passing test would be most welcome!

**Comment by biesbjerg** [comment] 2017-07-05 13:43
@BenDevelopment You correctly identified a problem where only the escaped quote was being replace. I will fix this.

As for @Toub, I can't reproduce your issue. When using your example in a template and running extract, I get the correct output:

Command
`ngx-translate-extract -i ./src -o test.po --format pot`

test.component.ts
```ts
@Component({
	template: `<span [title]=" 'C\'est ok' | translate"</span>`
})
export class TestComponent {
	public constructor(protected _translateService: TranslateService) { }
}
```

test.po
```po
msgid ""
msgstr ""
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"

msgid "C'est ok"
msgstr ""
```

**Comment by biesbjerg** [comment] 2017-07-05 13:44
Going to close this until more information is provided by @Toub.

@BenDevelopment Your fix has been committed here: https://github.com/biesbjerg/ngx-translate-extract/commit/b2ae17697dc9ebfccbd549ca95bdc0469017ee63

**Closed by biesbjerg** 2017-07-05 13:44 UTC
