### ISSUE TITLE
undefined being extracted

### ISSUE THREAD

**Issue by matheo** [biesbjerg/ngx-translate-extract#68] opened 2017-09-01 02:48 UTC
I have this `npm script` on my Angular project:
```
"extract": "ngx-translate-extract --input ./src --output ./src/assets/i18n/*.json --clean --sort --format namespaced-json --marker _ --fi '  '",
````
and I'm getting this on the final of my extracted `.json` file:
```
  },
  "undefined": ""
}
```
I've removed all the uses of `_` and the problem persists.
I thought that it would be ideal if the extractor filters that out.

Thanks for this awesome tool

**Comment by matheo** [comment] 2017-11-08 15:45
@biesbjerg Hi!
sorry to bother, but I think I got the issue:

I'm using `{{ myVar | translate }}` and that's probably why the extract script is getting `undefined` in the catalog. The simplest solution I imagine is to discard it while formatting the `.json` file.
Thanks again!

**Comment by Ismaestro** [comment] 2018-10-07 17:56
+1

**Comment by biesbjerg** [comment] 2019-06-13 10:58
Unable to reproduce. Please provide a component/template that causes this and I'd be happy to debug it. Closing for now

**Closed by biesbjerg** 2019-06-13 10:58 UTC
