### ISSUE TITLE
Can't extract from arrays

### ISSUE THREAD

**Issue by NatoBoram** [biesbjerg/ngx-translate-extract#166] opened 2020-02-13 21:32 UTC
Given the following snippet : 

```typescript
this.translate.get(['error.duplicate_choice', 'app.dismiss']).subscribe(text => {
  this.snackbar.open(text['error.duplicate_choice'], text['app.dismiss']);
});
```

The extractor doesn't work.

I have to use the following workaround : 

```typescript
this.translate.get([marker('error.duplicate_choice'), marker('app.dismiss')]).subscribe(text => {
  this.snackbar.open(text['error.duplicate_choice'], text['app.dismiss']);
});
```

**Comment by jochenjonc** [comment] 2020-03-04 08:10
Hi @NatoBoram,

Is was able to fix this issue by manually adjusting the entry of ngx-translate-extract in the package-lock.json. I replaced it again with a version that used to work.
After that, I removed my node_modules folder and run npm install.

To be honest, not all is fixed. Some keys are not extracted and I'm looking into it a bit more.

Below is an extract of my package-lock.json, the first is the broken one, the second is the one that solved most issues. You can also see the differences [here](https://www.diffchecker.com/nn0jM39R).

The faulty one:
``` json
    "@biesbjerg/ngx-translate-extract": {
      "version": "4.2.0",
      "resolved": "https://registry.npmjs.org/@biesbjerg/ngx-translate-extract/-/ngx-translate-extract-4.2.0.tgz",
      "integrity": "sha512-MY33zFNqlZFPv4RU5rCdyuvINwmwhWcGrxYy0MoiXsqLkqoly4xCt7cJhdSh3XhTi85dDi//hGynxGc5WzXnbA==",
      "dev": true,
      "requires": {
        "@angular/compiler": "^8.2.6",
        "@phenomnomnominal/tsquery": "^3.0.0",
        "boxen": "^4.1.0",
        "colorette": "^1.1.0",
        "flat": "github:lenchvolodymyr/flat#ffe77ef",
        "gettext-parser": "^4.0.2",
        "glob": "^7.1.4",
        "mkdirp": "^0.5.1",
        "path": "^0.12.7",
        "terminal-link": "^2.0.0",
        "typescript": "^3.6.3",
        "yargs": "^14.0.0"
      },
      "dependencies": {
        "cliui": {
          "version": "5.0.0",
          "resolved": "https://registry.npmjs.org/cliui/-/cliui-5.0.0.tgz",
          "integrity": "sha512-PYeGSEmmHM6zvoef2w8TPzlrnNpXIjTipYK780YswmIP9vjxmd6Y2a3CB2Ks6/AU8NHjZugXvo8w3oWM2qnwXA==",
          "dev": true,
          "requires": {
            "string-width": "^3.1.0",
            "strip-ansi": "^5.2.0",
            "wrap-ansi": "^5.1.0"
          }
        },
        "emoji-regex": {
          "version": "7.0.3",
          "resolved": "https://registry.npmjs.org/emoji-regex/-/emoji-regex-7.0.3.tgz",
          "integrity": "sha512-CwBLREIQ7LvYFB0WyRvwhq5N5qPhc6PMjD6bYggFlI5YyDgl+0vxq5VHbMOFqLg7hfWzmu8T5Z1QofhmTIhItA==",
          "dev": true
        },
        "find-up": {
          "version": "3.0.0",
          "resolved": "https://registry.npmjs.org/find-up/-/find-up-3.0.0.tgz",
          "integrity": "sha512-1yD6RmLI1XBfxugvORwlck6f75tYL+iR0jqwsOrOxMZyGYqUuDhJ0l4AXdO1iX/FTs9cBAMEk1gWSEx1kSbylg==",
          "dev": true,
          "requires": {
            "locate-path": "^3.0.0"
          }
        },
        "flat": {
          "version": "4.1.0",
          "from": "github:lenchvolodymyr/flat#ffe77ef",
          "bundled": true,
          "dev": true,
          "requires": {
            "is-buffer": "~2.0.3"
          }
        },
        "is-buffer": {
          "version": "2.0.3",
          "bundled": true,
          "dev": true
        },
        "is-fullwidth-code-point": {
          "version": "2.0.0",
          "resolved": "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-2.0.0.tgz",
          "integrity": "sha1-o7MKXE8ZkYMWeqq5O+764937ZU8=",
          "dev": true
        },
        "locate-path": {
          "version": "3.0.0",
          "resolved": "https://registry.npmjs.org/locate-path/-/locate-path-3.0.0.tgz",
          "integrity": "sha512-7AO748wWnIhNqAuaty2ZWHkQHRSNfPVIsPIfwEOWO22AmaoVrWavlOcMR5nzTLNYvp36X220/maaRsrec1G65A==",
          "dev": true,
          "requires": {
            "p-locate": "^3.0.0",
            "path-exists": "^3.0.0"
          }
        },
        "p-locate": {
          "version": "3.0.0",
          "resolved": "https://registry.npmjs.org/p-locate/-/p-locate-3.0.0.tgz",
          "integrity": "sha512-x+12w/To+4GFfgJhBEpiDcLozRJGegY+Ei7/z0tSLkMmxGZNybVMSfWj9aJn8Z5Fc7dBUNJOOVgPv2H7IwulSQ==",
          "dev": true,
          "requires": {
            "p-limit": "^2.0.0"
          }
        },
        "path-exists": {
          "version": "3.0.0",
          "resolved": "https://registry.npmjs.org/path-exists/-/path-exists-3.0.0.tgz",
          "integrity": "sha1-zg6+ql94yxiSXqfYENe1mwEP1RU=",
          "dev": true
        },
        "string-width": {
          "version": "3.1.0",
          "resolved": "https://registry.npmjs.org/string-width/-/string-width-3.1.0.tgz",
          "integrity": "sha512-vafcv6KjVZKSgz06oM/H6GDBrAtz8vdhQakGjFIvNrHA6y3HCF1CInLy+QLq8dTJPQ1b+KDUqDFctkdRW44e1w==",
          "dev": true,
          "requires": {
            "emoji-regex": "^7.0.1",
            "is-fullwidth-code-point": "^2.0.0",
            "strip-ansi": "^5.1.0"
          }
        },
        "strip-ansi": {
          "version": "5.2.0",
          "resolved": "https://registry.npmjs.org/strip-ansi/-/strip-ansi-5.2.0.tgz",
          "integrity": "sha512-DuRs1gKbBqsMKIZlrffwlug8MHkcnpjs5VPmL1PAh+mA30U0DTotfDZ0d2UUsXpPmPmMMJ6W773MaA3J+lbiWA==",
          "dev": true,
          "requires": {
            "ansi-regex": "^4.1.0"
          }
        },
        "typescript": {
          "version": "3.8.2",
          "resolved": "https://registry.npmjs.org/typescript/-/typescript-3.8.2.tgz",
          "integrity": "sha512-EgOVgL/4xfVrCMbhYKUQTdF37SQn4Iw73H5BgCrF1Abdun7Kwy/QZsE/ssAy0y4LxBbvua3PIbFsbRczWWnDdQ==",
          "dev": true
        },
        "wrap-ansi": {
          "version": "5.1.0",
          "resolved": "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-5.1.0.tgz",
          "integrity": "sha512-QC1/iN/2/RPVJ5jYK8BGttj5z83LmSKmvbvrXPNCLZSEb32KKVDJDl/MOt2N01qU2H/FkzEa9PKto1BqDjtd7Q==",
          "dev": true,
          "requires": {
            "ansi-styles": "^3.2.0",
            "string-width": "^3.0.0",
            "strip-ansi": "^5.0.0"
          }
        },
        "yargs": {
          "version": "14.2.2",
          "resolved": "https://registry.npmjs.org/yargs/-/yargs-14.2.2.tgz",
          "integrity": "sha512-/4ld+4VV5RnrynMhPZJ/ZpOCGSCeghMykZ3BhdFBDa9Wy/RH6uEGNWDJog+aUlq+9OM1CFTgtYRW5Is1Po9NOA==",
          "dev": true,
          "requires": {
            "cliui": "^5.0.0",
            "decamelize": "^1.2.0",
            "find-up": "^3.0.0",
            "get-caller-file": "^2.0.1",
            "require-directory": "^2.1.1",
            "require-main-filename": "^2.0.0",
            "set-blocking": "^2.0.0",
            "string-width": "^3.0.0",
            "which-module": "^2.0.0",
            "y18n": "^4.0.0",
            "yargs-parser": "^15.0.0"
          }
        },
        "yargs-parser": {
          "version": "15.0.0",
          "resolved": "https://registry.npmjs.org/yargs-parser/-/yargs-parser-15.0.0.tgz",
          "integrity": "sha512-xLTUnCMc4JhxrPEPUYD5IBR1mWCK/aT6+RJ/K29JY2y1vD+FhtgKK0AXRWvI262q3QSffAQuTouFIKUuHX89wQ==",
          "dev": true,
          "requires": {
            "camelcase": "^5.0.0",
            "decamelize": "^1.2.0"
          }
        }
      }
    },
```

The working one:
```json
    "@biesbjerg/ngx-translate-extract": {
      "version": "4.2.0",
      "resolved": "https://registry.npmjs.org/@biesbjerg/ngx-translate-extract/-/ngx-translate-extract-4.2.0.tgz",
      "integrity": "sha512-MY33zFNqlZFPv4RU5rCdyuvINwmwhWcGrxYy0MoiXsqLkqoly4xCt7cJhdSh3XhTi85dDi//hGynxGc5WzXnbA==",
      "dev": true,
      "requires": {
        "@angular/compiler": "^8.2.6",
        "@phenomnomnominal/tsquery": "^3.0.0",
        "boxen": "^4.1.0",
        "colorette": "^1.1.0",
        "flat": "github:lenchvolodymyr/flat#ffe77ef",
        "gettext-parser": "^4.0.2",
        "glob": "^7.1.4",
        "mkdirp": "^0.5.1",
        "path": "^0.12.7",
        "terminal-link": "^2.0.0",
        "typescript": "^3.6.3",
        "yargs": "^14.0.0"
      },
      "dependencies": {
        "ansi-regex": {
          "version": "4.1.0",
          "resolved": "https://registry.npmjs.org/ansi-regex/-/ansi-regex-4.1.0.tgz",
          "integrity": "sha512-1apePfXM1UOSqw0o9IiFAovVz9M5S1Dg+4TrDwfMewQ6p/rmMueb7tWZjQ1rx4Loy1ArBggoqGpfqqdI4rondg==",
          "dev": true
        },
        "cliui": {
          "version": "5.0.0",
          "resolved": "https://registry.npmjs.org/cliui/-/cliui-5.0.0.tgz",
          "integrity": "sha512-PYeGSEmmHM6zvoef2w8TPzlrnNpXIjTipYK780YswmIP9vjxmd6Y2a3CB2Ks6/AU8NHjZugXvo8w3oWM2qnwXA==",
          "dev": true,
          "requires": {
            "string-width": "^3.1.0",
            "strip-ansi": "^5.2.0",
            "wrap-ansi": "^5.1.0"
          }
        },
        "emoji-regex": {
          "version": "7.0.3",
          "resolved": "https://registry.npmjs.org/emoji-regex/-/emoji-regex-7.0.3.tgz",
          "integrity": "sha512-CwBLREIQ7LvYFB0WyRvwhq5N5qPhc6PMjD6bYggFlI5YyDgl+0vxq5VHbMOFqLg7hfWzmu8T5Z1QofhmTIhItA==",
          "dev": true
        },
        "flat": {
          "version": "4.1.0",
          "from": "github:lenchvolodymyr/flat#ffe77ef",
          "bundled": true,
          "dev": true,
          "requires": {
            "is-buffer": "~2.0.3"
          }
        },
        "get-caller-file": {
          "version": "2.0.5",
          "resolved": "https://registry.npmjs.org/get-caller-file/-/get-caller-file-2.0.5.tgz",
          "integrity": "sha512-DyFP3BM/3YHTQOCUL/w0OZHR0lpKeGrxotcHWcqNEdnltqFwXVfhEBQ94eIo34AfQpo0rGki4cyIiftY06h2Fg==",
          "dev": true
        },
        "is-buffer": {
          "version": "2.0.3",
          "bundled": true,
          "dev": true
        },
        "require-main-filename": {
          "version": "2.0.0",
          "resolved": "https://registry.npmjs.org/require-main-filename/-/require-main-filename-2.0.0.tgz",
          "integrity": "sha512-NKN5kMDylKuldxYLSUfrbo5Tuzh4hd+2E8NPPX02mZtn1VuREQToYe/ZdlJy+J3uCpfaiGF05e7B8W0iXbQHmg==",
          "dev": true
        },
        "string-width": {
          "version": "3.1.0",
          "resolved": "https://registry.npmjs.org/string-width/-/string-width-3.1.0.tgz",
          "integrity": "sha512-vafcv6KjVZKSgz06oM/H6GDBrAtz8vdhQakGjFIvNrHA6y3HCF1CInLy+QLq8dTJPQ1b+KDUqDFctkdRW44e1w==",
          "dev": true,
          "requires": {
            "emoji-regex": "^7.0.1",
            "is-fullwidth-code-point": "^2.0.0",
            "strip-ansi": "^5.1.0"
          }
        },
        "strip-ansi": {
          "version": "5.2.0",
          "resolved": "https://registry.npmjs.org/strip-ansi/-/strip-ansi-5.2.0.tgz",
          "integrity": "sha512-DuRs1gKbBqsMKIZlrffwlug8MHkcnpjs5VPmL1PAh+mA30U0DTotfDZ0d2UUsXpPmPmMMJ6W773MaA3J+lbiWA==",
          "dev": true,
          "requires": {
            "ansi-regex": "^4.1.0"
          }
        },
        "typescript": {
          "version": "3.6.4",
          "resolved": "https://registry.npmjs.org/typescript/-/typescript-3.6.4.tgz",
          "integrity": "sha512-unoCll1+l+YK4i4F8f22TaNVPRHcD9PA3yCuZ8g5e0qGqlVlJ/8FSateOLLSagn+Yg5+ZwuPkL8LFUc0Jcvksg==",
          "dev": true
        },
        "wrap-ansi": {
          "version": "5.1.0",
          "resolved": "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-5.1.0.tgz",
          "integrity": "sha512-QC1/iN/2/RPVJ5jYK8BGttj5z83LmSKmvbvrXPNCLZSEb32KKVDJDl/MOt2N01qU2H/FkzEa9PKto1BqDjtd7Q==",
          "dev": true,
          "requires": {
            "ansi-styles": "^3.2.0",
            "string-width": "^3.0.0",
            "strip-ansi": "^5.0.0"
          }
        },
        "yargs": {
          "version": "14.2.0",
          "resolved": "https://registry.npmjs.org/yargs/-/yargs-14.2.0.tgz",
          "integrity": "sha512-/is78VKbKs70bVZH7w4YaZea6xcJWOAwkhbR0CFuZBmYtfTYF0xjGJF43AYd8g2Uii1yJwmS5GR2vBmrc32sbg==",
          "dev": true,
          "requires": {
            "cliui": "^5.0.0",
            "decamelize": "^1.2.0",
            "find-up": "^3.0.0",
            "get-caller-file": "^2.0.1",
            "require-directory": "^2.1.1",
            "require-main-filename": "^2.0.0",
            "set-blocking": "^2.0.0",
            "string-width": "^3.0.0",
            "which-module": "^2.0.0",
            "y18n": "^4.0.0",
            "yargs-parser": "^15.0.0"
          }
        },
        "yargs-parser": {
          "version": "15.0.0",
          "resolved": "https://registry.npmjs.org/yargs-parser/-/yargs-parser-15.0.0.tgz",
          "integrity": "sha512-xLTUnCMc4JhxrPEPUYD5IBR1mWCK/aT6+RJ/K29JY2y1vD+FhtgKK0AXRWvI262q3QSffAQuTouFIKUuHX89wQ==",
          "dev": true,
          "requires": {
            "camelcase": "^5.0.0",
            "decamelize": "^1.2.0"
          }
        }
      }
    },
```

To actually solve this issue I think the dependencies within the ngx-translate-extract package need to be adjusted.

**Comment by biesbjerg** [comment] 2020-03-08 09:12
@NatoBoram Could you please provide a full example of the file where values are not extracted from?

**Comment by biesbjerg** [comment] 2020-03-19 10:23
Closing since I cannot reproduce.

**Closed by biesbjerg** 2020-03-19 10:23 UTC

**Comment by jochenjonc** [comment] 2020-03-20 14:10
@biesbjerg today I upgraded to v5.0.0 and the problem returned. I'll try to make an example later today.

**Comment by jochenjonc** [comment] 2020-03-23 07:57
@biesbjerg I think the problem is Angular 8.2.3 and Typescript 3.5.3. I've seen that you require higher version on both.

**Comment by biesbjerg** [comment] 2020-03-23 10:14
Could you provide a sample app where translations are not extracted correctly? Then I’ll be happy to take a look 😊

**Comment by jochenjonc** [comment] 2020-03-27 10:37
I upgraded my project to Angular 9 and also installed the latest ngx-translate-extract and everything is working fine now.

**Comment by biesbjerg** [comment] 2020-03-27 10:38
Good to hear, @jochenjonc :)
