### ISSUE TITLE
Bug with latest version 4.2.0 "TypeError: Cannot read property 'kind' of undefined"

### ISSUE THREAD

**Issue by bagage** [biesbjerg/ngx-translate-extract#140] opened 2019-09-19 08:15 UTC
It was working previously with `  ngx-translate-extract --fi \"    \" --sort --format namespaced-json --clean --marker _ --input ./src --output ./src/assets/i18n/cs-CZ.json` but now it yields:

```
/home/proj/src/node_modules/@biesbjerg/ngx-translate-extract/node_modules/typescript/lib/typescript.js:15433
        return node.kind === 10 /* StringLiteral */ || node.kind === 14 /* NoSubstitutionTemplateLiteral */;
                    ^

TypeError: Cannot read property 'kind' of undefined
    at Object.isStringLiteralLike (/home/proj/src/node_modules/@biesbjerg/ngx-translate-extract/node_modules/typescript/lib/typescript.js:15433:21)
    at Object.getStringsFromExpression (/home/proj/src/node_modules/@biesbjerg/ngx-translate-extract/dist/utils/ast-helpers.js:72:22)
    at Object.getStringsFromExpression (/home/proj/src/node_modules/@biesbjerg/ngx-translate-extract/dist/utils/ast-helpers.js:104:33)
    at callNodes.forEach.callNode (/home/proj/src/node_modules/@biesbjerg/ngx-translate-extract/dist/parsers/service.parser.js:27:47)
    at Array.forEach (<anonymous>)
    at classNodes.forEach.classNode (/home/proj/src/node_modules/@biesbjerg/ngx-translate-extract/dist/parsers/service.parser.js:22:23)
    at Array.forEach (<anonymous>)
    at ServiceParser.extract (/home/proj/src/node_modules/@biesbjerg/ngx-translate-extract/dist/parsers/service.parser.js:16:20)
    at parsers.forEach.parser (/home/proj/src/node_modules/@biesbjerg/ngx-translate-extract/dist/cli/tasks/extract.task.js:77:46)
    at Array.forEach (<anonymous>)
```

**Comment by biesbjerg** [comment] 2019-09-19 09:34
Can you post the input file where the error occur happens?

**Comment by biesbjerg** [comment] 2019-10-06 10:46
Closing since I can't reproduce.

**Closed by biesbjerg** 2019-10-06 10:46 UTC
Labels: info needed

**Comment by TheTonnio** [comment] 2020-10-14 11:06
I have the same issue. It occurs because your project has a newer typescript version than that package.
Solution: update `biesbjerg/ngx-translate-extract` to the latest version.
