### ISSUE TITLE
wrong implementation of extract function

### ISSUE THREAD

**Issue by WuglyakBolgoink** [biesbjerg/ngx-translate-extract#215] opened 2020-09-28 17:47 UTC
or I need to do some other steps?

what I have
```html
<p translate>Every day you can send up to 10 requests directly through this platform<br>
     <strong>Your have {{limit}} request(s) left.</strong> If it becomes equal to 0, you still will be able to search.
</p>
```

what I have after `extract`

```json
{
    ...,
    "Every day you can send up to 10 requests directly through this platform": "Every day you can send up to 10 requests directly through this platform",
    "If it becomes equal to 0, you still will be able to search.": "If it becomes equal to 0, you still will be able to search.",
    ...,
}
```

where is `<strong>Your have {{limit}} request(s) left.</strong>`??? And we have many other examples with this missed texts...

what we expected
```json
{
    ...,
    "Every day you can send up to 10 requests directly through this platform<br><strong>Your have {{limit}} request(s) left.</strong> If it becomes equal to 0, you still will be able to search.": "Every day you can send up to 10 requests directly through this platform<br><strong>Your have {{limit}} request(s) left.</strong> If it becomes equal to 0, you still will be able to search.",
    ...,
}
```

also, extracter should take full content of any html-tag with `translate`-directive and replace line breaks with spaces and use this as a key/value in result files., but not splitting it if any html tag was inside of the root-tag...

**Comment by biesbjerg** [comment] 2020-09-29 09:54
Hi!

`ngx-translate`'s `translate`-directive only translates direct text nodes of the html-element where the directive is present.

See tests here: https://github.com/ngx-translate/core/blob/master/projects/ngx-translate/core/tests/translate.directive.spec.ts#L93-L111

If `ngx-translate-extract` extracted keys in any other way than it currently does, the resulting keys wouldn't match up with what `ngx-translate` is looking for in the language files.

Closing since it is working as intended.

**Closed by biesbjerg** 2020-09-29 09:54 UTC
