### ISSUE TITLE
Problem using the marker function with angular cli

### ISSUE THREAD

**Issue by ht89** [biesbjerg/ngx-translate-extract#63] opened 2017-07-14 04:27 UTC
Hello, 
Would you please help me with this error? It happens when I mark a string for extraction. Thanks a lot.
` /home/bbv/BBV/Client/node_modules/@biesbjerg/ngx-translate-extract/dist/cli/cli.d.ts (1,1): Cannot find type definition file for 'yargs'.`

**Comment by shrewmus** [comment] 2017-07-17 08:21
@ht89 
I've put strings and marker function calls in to separate file. After that in the "tsconfig.app.json" I've placed this file to "exclude" section

that works for me

**Comment by ht89** [comment] 2017-07-17 08:47
Hello @shrewmus, 
Thanks a lot for your help. Best regards.

**Comment by rybaczewa** [comment] 2017-07-20 14:18
That's only a workaround though, solution is hard to maintain with bigger projects. Possibly related to this: https://github.com/biesbjerg/ngx-translate-extract/issues/55

**Comment by matheo** [comment] 2017-07-31 23:04
I've installed `@types/yargs` as a devDependency and it passed,
BUT now I get a harder and deeper error:
```
ERROR in ./~/execa/index.js
Module not found: Error: Can't resolve 'child_process' in '/media/work/git/selvera/provider/node_modules/execa'
 @ ./~/execa/index.js 2:21-45
 @ ./~/@biesbjerg/ngx-translate-extract/~/os-locale/index.js
 @ ./~/@biesbjerg/ngx-translate-extract/~/yargs/yargs.js
 @ ./~/@biesbjerg/ngx-translate-extract/~/yargs/index.js
 @ ./~/@biesbjerg/ngx-translate-extract/dist/cli/cli.js
 @ ./~/@biesbjerg/ngx-translate-extract/dist/index.js
 @ ./src/app/layout/sidenav/sidenav.component.ts
 @ ./src/app/layout/index.ts
 @ ./src/app/layout/layout.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4201 ./src/main.ts

ERROR in ./~/execa/~/cross-spawn/index.js
Module not found: Error: Can't resolve 'child_process' in '/media/work/git/selvera/provider/node_modules/execa/node_modules/cross-spawn'
 @ ./~/execa/~/cross-spawn/index.js 3:9-33
 @ ./~/execa/index.js
 @ ./~/@biesbjerg/ngx-translate-extract/~/os-locale/index.js
 @ ./~/@biesbjerg/ngx-translate-extract/~/yargs/yargs.js
 @ ./~/@biesbjerg/ngx-translate-extract/~/yargs/index.js
 @ ./~/@biesbjerg/ngx-translate-extract/dist/cli/cli.js
 @ ./~/@biesbjerg/ngx-translate-extract/dist/index.js
 @ ./src/app/layout/sidenav/sidenav.component.ts
 @ ./src/app/layout/index.ts
 @ ./src/app/layout/layout.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4201 ./src/main.ts
```

This package can somehow configure execa to not use "child_processes" on webpack, only in Node's CLI?

**Comment by giathinh910** [comment] 2017-08-03 07:40
My solution is to create a very simple function with the same name "_" like this:
```typescript
export function _(str) {
  return str;
}
```
then just use:
```typescript
translationKeys = {
    usernameRequired: _('Username is required!'),
    passwordRequired: _('Password is required!'),
    newPasswordRequired: _('New password is required!'),
    confirmedNewPasswordNotMatched: _('Confirmed password is not matched!')
  };
````
then run the extractor with marker option as the doc said, the extractor will fine your texts. Good luck.

**Comment by rybaczewa** [comment] 2017-08-03 07:46
@giathinh910 I've tried that and it extracts strings, but doesn't translate them on call. I would expect `translationKeys.usernameRequired` to be translated, you need to call translate function every time you reference it IIRC. So it works for extraction, not so for translation.

**Comment by giathinh910** [comment] 2017-08-03 08:00
@rybaczewa Yeah, my solution is for resolving problem of @ht89 when using marker function with angular cli. In order to translate, just follow the doc, mine worked fine.

Just get the default text when init component using that key
```typescript
this.translate.get([
      this.translationKeys.usernameRequired
]).subscribe((res: string[]) => {
      console.log(res[this.translationKeys.usernameRequired]);
});
```
Then subscribe the language change event to get the translation text when you change lang
```typescript
this.translate.onLangChange.subscribe((event: LangChangeEvent) => {
      console.log(event.translations[this.translationKeys.usernameRequired]);
});
```

**Comment by kuiperr005** [comment] 2017-08-25 13:06
@biesbjerg do you know a solution for this? I think more people will experience this issue. 
I'm also using webpack and I'm using the [AngularClass/Starter](https://github.com/AngularClass/angular-starter)

**Comment by challe** [comment] 2017-09-07 14:52
@biesbjerg I aso just ran into this now

**Comment by V1Ray** [comment] 2017-10-06 15:02
@matheo, I have the same problem. 
How to solve this problem?

**Comment by killerchip** [comment] 2017-10-12 16:27
@giathinh910 works like a charm. I have tested it with AOT also.

**Comment by raphael22** [comment] 2018-01-12 13:33
@biesbjerg Same issue with ionic 3+

**Comment by bedag-moo** [comment] 2018-01-17 19:51
We just ran into this as well. The cause was that our IDE generated the import 

    import {_} from "@biesbjerg/ngx-translate-extract";

rather than

    import {_} from "@biesbjerg/ngx-translate-extract/dist/utils/utils";

As a consequence, webpack pulled the entire code of ngx-translate-extract into the classpath (no clue why tree shaking didn't work), and failed upon analysing some transitive dependencies. The 
[resulting stack trace](https://github.com/biesbjerg/ngx-translate-extract/files/1640356/ugly-stack-trace.txt) was not pretty, and left the developer mystified.

Of course, it is entirely unnecessary to load the entire extraction tool at runtime if we just want this single function ... would it be possible to exclude the marker function from dist/index.js so IDEs only suggest the harmless deep import?

**Comment by MickL** [comment] 2019-05-15 12:24
Guys just use the correct import as @bedag-moo suggested:

`import {_} from '@biesbjerg/ngx-translate-extract/dist/utils/utils';`

**Comment by biesbjerg** [comment] 2019-06-24 10:54
I've created a separate package for the marker function.

`npm install @biesbjerg/ngx-translate-extract-marker`

```ts
import { marker } from '@biesbjerg/ngx-translate-extract-marker';
```

**Closed by biesbjerg** 2019-06-24 10:54 UTC
